### ISSUE TITLE
Include could not find requested file: UploadMethodJ-Link

### ISSUE THREAD

**Issue by maiorfi** [mbed-ce/mbed-os#35]
Hi.

Following your guide for VSCode here: https://github.com/mbed-ce/mbed-os/wiki/Project-Setup:-VS-Code I have an error while running "CMake: Set Build Target" step (as well as when I try to build project anyway).

Error is:
```
[main] Unable to determine what CMake generator to use. Please install or configure a preferred generator, or update settings.json, your Kit configuration or PATH variable. Error: No usable generator found.
```

I have installed all required components (toolchain, vscode extensions, tools, etc).

Kit scanning detected my GCC 10.3.1 arm-none-eabi toolchain correctly.

cmake-variants.yaml I am using is following:

```yaml
buildType:
  default: Develop
  choices:
    Develop:
      short: Develop
      long: Emit debug information but also optimize
      buildType: Develop
    Debug:
      short: Debug
      long: Emit debug information and don't optimize
      buildType: Debug
    Release:
      short: Release
      long: Optimize generated code
      buildType: Release
board:
  default: DISCO_L475VG_IOT01A
  choices:
    DISCO_L475VG_IOT01A:
      short: DISCO_L475VG_IOT01A
      settings:
        MBED_TARGET: DISCO_L475VG_IOT01A
        UPLOAD_METHOD: J-Link
```

Any hint?

Thanks!
